PLOT_HEIGHT = 700
PLOT_WIDTH = 1000
RANDOM_GENERAL_COLOR = "Blue"
META_LEARNING_COLOR = "Purple"
RANDOM_DATA_SPECIFIC_COLOR = "Green"
COST_MODEL_WEIGHTED_RANDOM_COLOR = "Red"
NO_OPTION = "No"
YES_OPTION = "Yes"